language: node_js
node_js:
    - "12.13"
before_script:
    - npm run test
after_success:
    - npm run build
before_deploy:
    - mv package.json dist/package.json
    - mv readme.md dist/readme.md
    - mv LICENSE dist/LICENSE
    - cd dist
deploy:
    provider: npm
    email: aneke1234@gmail.com
    api_key:
        secure: NcsOyx683ZzDtBxlihhPThnLln+tHtzxzz4liLv1d+pAugt/l2ZFExzUb+LZ0E/4aYM/gk8AIggERpweFNMyFGim+ZAqwoeL9JobdnvIvy1gCNfgg/+Dz0LXd0m9vDL4P4aOBfuu+123W9ZuFZqTGCxs4zGyEPDhsHcZ4fApnfJJS78RJ8eqBeZoPeUDvLxb+QQIuqSqdVLV7MXoajlkunj/wsbfK7RIJfwPNC9cMHkYH7cHd8KImVWJ5EQgwTv399+hjEZRb3M8R3hTuSBNbP9+s+f8M2A3zqVeEYyOCfP3Fe5qbgrUHBLwTRKZqtcHop+RLaBGV1osy7dt8InGF2WtkbKeTK1SzbCTlQEN78Nav0id0JaOQwVNLZEYadJ4IPbZDXeZ4jsXXjjkPItN32vx9OpQPOFOe8qEQ3atPcE1649AaTReAXIehObA0yfGezUk2g8DCcABEMSrcygO50IWZk54ZieMnQA6z47KLxAde3n1WdQWEBe8VpWUznClFZG+Va9v5CQ/BG49kGNnz8uU8eMwLK5EbkEIqlamw5xF7t1tyYPKYAbaly885Nf0IggiEhXqhR2PL9yN4do7CN9LKybE9g0wP48Jd+Wfmg71SzbydoA4hBlECeeHDzJmK+UIjjdoXJYnxzX+gICh8AO3oLKyMhk2NcedjWc5TaQ=
    on:
        tags: true
        repo: ankeris/RediSearchFuzzy
        branch: production
    skip_cleanup: "true"
