language: node_js
node_js:
    - "12.13"
before_script:
    - npm run test
after_success:
    - npm run build
before_deploy:
    - mv package.json dist/package.json
    - mv readme.md dist/readme.md
    - mv LICENSE dist/LICENSE
    - cd dist
deploy:
    provider: npm
    email: aneke1234@gmail.com
    api_key:
        secure: bF4hIKm9kaUZjnnvp57L0AFeYyh0eNiFDcxKSN8+ACSexjjTyzSWNQS8KnIV3xiSXEWLXt/VxC5cn5OH6mzPEO4AAKBOShN2Xr/uzeDzekhnJQrRDCZpmqJNqlNnabc4pCVHReWrGIdsV9YLcn76+qn7XxjS37xxLhUu5rVRV0vADVISkubm3Kcu/PNv3Znzh90yDlWg3kUidsKI09GdrCMhiNnm49dQkitgCTXqtuUMmKiHzIL5HFxytFgZqA9bcf7weHQXVGRPzE39iAxXIcGTiCtZ4ku0Rr1Et2azIahVGTvJAiCjLDiIR2kCCKIYf8Gbby2bubw+eH+IsY7jdQ57ol/Yxx+sH/I8mZxCzFiJSoBY58ocCcCp549h1ubhKtxb9SOXmXjO8NQNmHAWlUEcRPyv+qaQH7hP3NtaswmWLCQ5s4ot3S72RGwbo+6bxaQ19ujjMX3wnd838t/3eI+kc+S3sDAbZAgGhSrevZLR8ptfUvKLV0qkezVvb3/KLn22+7Jl/3mDB+0Sn/Qfi7nWHBVENUV1FMAK1DAkiBIZxUlvx8gvs4nQRrhp4kWYDWZhZueOQ3VGO2ITSBzlB0EXFY46VWR9ljJjMFb9ZevQ5n+AtUwPp2ZI5Oz2EqMa2PXfYcyoaJRHpTmPUcWUyvpAW/3+2r9W5HUpXZhdFMc=
    on:
        tags: true
        repo: ankeris/RediSearchFuzzy
        branch: production
    skip_cleanup: "true"
