language: node_js
node_js:
    - "12.13"
before_script:
    - npm run test
after_success:
    - npm run build
before_deploy:
    - mv package.json dist/package.json
    - mv readme.md dist/readme.md
    - mv LICENSE dist/LICENSE
    - cd dist
deploy:
    provider: npm
    email: YOUR_EMAIL_ADDRESS
    skip_cleanup: true
    api_key:
        secure: ZMCH0V6dTWH1Dej/6PsmY4Ayzspciv8TSpbNcIaJCfX2X7KQiTzN+rQsTSOJOL4wqtL+hvaQ3N76rwGdvYDkP+8yV0F20JSUBdGApLiRqiXxUmL+ZwlDnjuYT9K/b4TNg/w/XViNdADoCnBEXq40dC7vD8vUOqI0y2XxDiwPMF/4l9er73GpzlnUch8oem9ELZYPD1RsE/zk8mhHWEOPBOX/3TxLbSpagzpDOFDpP+5B88oEQGu4lQmy3DjlzgmsX7/UQat+iCqcc9byj2cM8IMp6Ubxmq+vwCojN4Sx3nvsv04jirl57OD4FeAcVak4jFKx2fUYJDp327B8vUZx0jM5KOO/1wdd0iDxaVTNh3+R91Xx8ArF/DeikUPgh/HYWIZBEumkMogWkECjeWsIi77lPwrNMYizfq3CUyTbGYyLULOZ8JKNzZFY14mpl0jvCtajg7RVdxHlVJj94o+SKg5DTuMj+gfvFJh/QePvqBfZvqbePywCEm9JXI1NqxwNSSnkK8riC67TD3fBBs12NLikTXDzxAWUHhMq/ovFPa2WX7hEGT6OG7AUvoK9cPvFjKvVePcgs5x3r702KPaQGYxZ9NGiFwZ3fIHXz/QZwTRjr/3l/Q4pyrJYzm+EHN3ZVcHCSfuXTH1bm4k9KsUgNuW3orKl45MOtAETVp4GWs0=
    on:
        tags: true
        branch: production
