language: node_js
node_js:
    - "12.13"
before_script:
    - npm run test
after_success:
    - npm run build
before_deploy:
    - cp package.json dist/package.json
    - cp readme.md dist/readme.md
    - cp LICENSE dist/LICENSE
    - cd dist
    - ls
deploy:
    provider: npm
    email: aneke1234@gmail.com
    api_key:
        secure: A0NLRBq19/DQqf7nNz1N2KalpJUl72Q6YeARiZUHqYzDP0A7oVlok1PsfJHKomLLJtWYPLnDH+BXg4vSw0bfrAVfMPypxRJ/ku1DNeN7kdcWbFxNmSgiA5HJTyXFuAngZEKE22HBFUc/Qk3k3rirALe/u+9lPFJE51YtnpaDsdgUyQXlazL2OaJq2jN+VJf9DMLb9MXwj6/TsEUN46bnecvbWd0rJeLbXOvyFwuEvG9YXgoz5xNZXorqP+O4NZCzXycOhtIUndreArpa6cWXP632SHgKygHphv/UoaZDPk8UfIZg9d6+FlOXBNAFuZ/1zefdcqXBiaL4dFpo/9+uXY68vwLYQTBzi9H2EHBlGMOm7QBb42UPS/Q7Wsw3igzya7GrK5sfrJEyBnj+RmefddOGLL9GXkRZ+/a/5MthU7z77ekjUs4VO0qVicgSzj9HZEjad176nEi4Mar7L1Rx8SNwOKtkxqsPeqX0gaRt+Eec5uYWcaD+OcIkK1vy6YZsljBiW/G1jAhhhUrWjtOATyttunt0O1NYdO+HDHz482gshUPgrMPe+htwDUO5K8sAtISgmTnwm9Z0vARnhpVPP+pfakVYBUBtn6e3NkcJq20WKxIt5/gzPxEShkekUk+VsimEA3pCdG7s64jvB3BgEpjhG8ogRyVgyu0yBdickVE=
    on:
        tags: true
        repo: ankeris/RediSearchFuzzy
        branch: production
    skip_cleanup: "true"
after_deploy:
    - cd ..
